name: Redcar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        build: [ linux, windows, mac, minimal, default ]
        include:
          - build: linux
            os: ubuntu-latest
            rust: "stable"
            features: "full"
          - build: mac
            os: macos-latest
            rust: "stable"
            features: "full"
          - build: minimal
            os: ubuntu-latest
            rust: "stable"
            features: "minimal"
          - build: default
            os: ubuntu-latest
            rust: "stable"
            features: "default"

    continue-on-error: ${{ matrix.rust != 'stable' }}
    runs-on: ${{ matrix.os }}
    #runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Build
        run: make build
      #- uses: actions/checkout@v2
      #- name: Build
      #  run: cargo build --verbose
      #  with:
      #    toolchain: ${{ matrix.rust }}
      #    profile: minimal
      #    override: true
      - name: Run tests
        run: cargo test --verbose
